### ISSUE TITLE
Custom actions do not work without exportable or searchable

### ISSUE THREAD

**Issue by mydeadlyvenoms** [omnifaces/optimusfaces#18]
`<ui:define name="actions">`...`</ui:define>` does not work without setting `exportable` or `searchable` to true.

**Comment by BalusC** [comment]
This is less or more a technical limitation. It's not possible to check whether a specific `<ui:define>` is defined. In order to support alone `<ui:define name="actions">` without searchable/exportable, it would be necessary to always declare the `<f:facet name="header">` of the underlying `<p;dataTable>`. But its renderer has the nasty behavior that it will always add some markup to it even though its contents is empty (i.e. when you aren't at all using searchable/exportable/actions), resulting in a slightly odd looking empty header.

I'll have to muse a bit on the best approach first.

**Comment by BalusC** [comment]
I have added `<op:dataTable ... actionable="true">` for this specific case.

Not nice, but there's no other way without JSF impl specific hacks.

**Comment by mydeadlyvenoms** [comment]
Hi @BalusC thank you for your help, unfortunately the `actionable` param seems not to trigger as the `<ui:define name="actions">` is still gone after removing exportable and searchable. Am I missing something?

**Comment by BalusC** [comment]
Build failed so the SNAPSHOT JAR with the fix wasn't created. I will fix failing build later.
