### ISSUE TITLE
Filtering on 'boolean' and 'bigint' does not work

### ISSUE THREAD

**Issue by mydeadlyvenoms** [omnifaces/optimusfaces#29]
Hi everyone

I did a few experiments using the latest release and found out that filtering on non Strings seems to be broken. Am I missing something or is this already known? According to the documentation this should actually work. 

Thank you very much for your help!

# 'boolean'
```
Local Exception Stack: 
Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.4.payara-p2): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: function lower(boolean) does not exist
  Hinweis: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 162
Error Code: 0
...
```

# 'bigint'
```
Local Exception Stack: 
Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.4.payara-p2): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: function lower(bigint) does not exist
  Hinweis: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 129
Error Code: 0
...
```

**Comment by kukel** [comment]
I have Enums and a Date and those fails as well. Will look into this.  Is your type boolean or Boolean? (and BigInt I assume)

**Comment by mydeadlyvenoms** [comment]
It is actually a `boolean` and a `long`, I used the terms of Postgres sorry.

**Comment by BalusC** [comment]
I'll take a look :+1:

**Comment by BalusC** [comment]
This problem is two-fold: 

1) EclipseLink doesn't support [`Expression#as()`](https://jakarta.ee/specifications/persistence/2.2/apidocs/javax/persistence/criteria/Expression.html#as(java.lang.Class)) (Hibernate does)
2) PostgreSQL is quite strict when query tries to convert a specific type to string so `LIKE` could be used. This is transparently performed/tolerated in H2 and MySQL without needing to explicitly cast the value.

This all takes place in [`JPA#castAsString()`](https://github.com/omnifaces/omnipersistence/blob/develop/src/main/java/org/omnifaces/persistence/JPA.java#L334) of OmniPersistence. So it needs to be fixed/improved over there.

@kukel As to `Enum`, you really need `@Enumerated(STRING)` on them for now. I'll look for improvements here. Update: this appears to be already [implemented](https://github.com/omnifaces/omnipersistence/blob/develop/src/main/java/org/omnifaces/persistence/criteria/Like.java#L76) for ordinal based enums .. What type exactly was it? Are you referring to PostgreSQL `enum` type? https://www.postgresql.org/docs/9.1/datatype-enum.html

As to `Date`, which type exactly was it? As of now the `JPA#castAsString()` only supports `LocalDate`/`LocalTime`/`LocalDateTime`/`OffsetTime`/`OffsetDateTime` (so no `ZonedDateTime`/`Instant` for now). I'll look how it can be improved. Update: it appears PostgreSQL doesn't support these: https://jdbc.postgresql.org/documentation/head/8-date-time.html

**Comment by BalusC** [comment]
I've fixed it in OmniPersistence side, it indeed didn't support primitive types.

**Comment by mydeadlyvenoms** [comment]
Hi @BalusC I did a few tests and it looks like there are still some issues with respect to 'long'. But the exception is different. I'll test the booleans now.

# long
```
Local Exception Stack: 
Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.4.payara-p2): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: operator does not exist: bigint ~~ character varying
  Hinweis: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 136
Error Code: 0
...
```
